// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Models;

namespace Movies.Migrations
{
    [DbContext(typeof(MovieAppContext))]
    [Migration("20230221015958_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Movies.Models.MovieSubmissionModel", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Sci-Fi",
                            Director = "George Lucas",
                            Edited = false,
                            Lent = "No",
                            Notes = "",
                            Rating = "PG",
                            Title = "Star Wars: Attack of the Clones",
                            Year = 2002
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Sci-Fi",
                            Director = "Taika Watiti",
                            Edited = false,
                            Lent = "No",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "Jojo Rabbit",
                            Year = 2019
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Sci-Fi",
                            Director = "Christopher Nolan",
                            Edited = false,
                            Lent = "No",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "Interstellar",
                            Year = 2011
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
