// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Models;

namespace Movies.Migrations
{
    [DbContext(typeof(MovieAppContext))]
    partial class MovieAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Movies.Models.MovieSubmissionModel", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovieId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Edited = false,
                            Lent = "No",
                            Notes = "Star Wars: Attack of the Clones",
                            Rating = "PG"
                        },
                        new
                        {
                            MovieId = 2,
                            Edited = false,
                            Lent = "No",
                            Notes = "Jojo Rabbit",
                            Rating = "PG-13"
                        },
                        new
                        {
                            MovieId = 3,
                            Edited = false,
                            Lent = "No",
                            Notes = "Interstellar",
                            Rating = "PG-13"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
